import Head from 'next/head';
import { useRouter } from 'next/router'
import Header from '../components/Header';
import Link from 'next/link';
import { useEffect } from 'react';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    router.push('/product/123');
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header /> 
        
      <Link href="/product/123">Go to product</Link> 
    </div>
  )
}
